services:
  registry:
    image: registry:2
    container_name: IMAGE_REGISTRY
    restart: unless-stopped
    ports:
      - ${TAILSCALE_IP}:5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
    volumes:
      - registry_data:/var/lib/registry

  grafana:
    image: grafana/grafana:latest
    container_name: GRAFANA 
    restart: unless-stopped
    ports:
      - ${TAILSCALE_IP}:23000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: PROMETHEUS
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/config.yml
    ports:
      - ${TAILSCALE_IP}:29090:9090
    volumes:
      - ./conf/prometheus/config.yml:/etc/prometheus/config.yml:ro
      - prometheus_data:/prometheus

  loki:
    image: grafana/loki:latest
    container_name: LOKI
    restart: unless-stopped
    user: 10001:10001
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr
    ports:
      - ${TAILSCALE_IP}:23100:3100
    volumes:
      - ./conf/loki/config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki

  alloy:
    image: grafana/alloy:latest
    container_name: ALLOY
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy
    ports:
      - ${TAILSCALE_IP}:12345:12345
    volumes:
      - ./conf/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ./log:/var/log/alloy:ro
      - alloy_data:/var/lib/alloy

  tempo:
    image: grafana/tempo:latest
    container_name: TEMPO
    restart: unless-stopped
    command:
      - --config.file=/etc/tempo/tempo.yaml
    ports:
      - ${TAILSCALE_IP}:24317:4317
      - ${TAILSCALE_IP}:24318:4318
      - ${TAILSCALE_IP}:23200:3200
    volumes:
      - ./conf/tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo_data:/var/tempo

  node-exporter:
    image: prom/node-exporter:latest
    container_name: NODE_EXPORTER
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    command: 
      - --path.rootfs=/host

volumes:
  registry_data:
  grafana_data:
  prometheus_data:
  loki_data:
  alloy_data:
  tempo_data:
