services:
  edge:
    image: caddy:2.11.3-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf/edge.Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - anubis

  anubis:
    image: ghcr.io/techarohq/anubis:latest
    pull_policy: always
    environment:
      BIND: ":8923"
      METRICS_BIND: ":9090"
      TARGET: "http://blog:80"
      DIFFICULTY: "4"
      SERVE_ROBOTS_TXT: "true"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    expose:
      - "8923"
      - "9090"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
    volumes:
      - "./conf/anubis.botPolicy.yaml:/data/cfg/botPolicy.yaml:ro"
    depends_on:
      - blog 

  blog:
    image: caddy:2.11.3-alpine
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./conf/blog.Caddyfile:/etc/caddy/Caddyfile:ro
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
