services:
  registry:
    image: registry:2
    container_name: internal-application-registry
    restart: unless-stopped
    ports:
      - 127.0.0.1:27000:5000
    environment:

      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000

    volumes:
      - registry-data:/var/lib/registry
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/v2/" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  registry-data:

networks:
  default:
    name: internal-application-network
    external: true
