services:
  grafana:
    image: grafana/grafana:latest
    container_name: internal-observability-grafana
    restart: unless-stopped
    ports:
      - 127.0.0.1:25000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  prometheus:
    image: prom/prometheus:latest
    container_name: internal-observability-prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/config.yml
    ports:
      - 127.0.0.1:25010:9090
    volumes:
      - ./conf/prometheus/config.yml:/etc/prometheus/config.yml:ro
      - prometheus-data:/prometheus
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/ready" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    extra_hosts:
      - host.docker.internal:host-gateway

  loki:
    image: grafana/loki:latest
    container_name: internal-observability-loki 
    restart: unless-stopped
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr
    ports:
      - 127.0.0.1:25020:3100
    volumes:
      - ./conf/loki/config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    healthcheck:
      test: [ "CMD", "/usr/bin/loki", "-health", "--health.url=http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  alloy:
    image: grafana/alloy:latest
    container_name: internal-observability-alloy
    restart: unless-stopped
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy
      - /etc/alloy/config.alloy
    ports:
      - 127.0.0.1:25030:12345
    volumes:
      - ./conf/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - alloy-data:/var/lib/alloy

  tempo:
    image: grafana/tempo:latest
    container_name: internal-observability-tempo
    restart: unless-stopped
    command:
      - --config.file=/etc/tempo/tempo.yaml
    ports:
      - 127.0.0.1:25040:4317
      - 127.0.0.1:25041:4318
      - 127.0.0.1:25042:3200
    volumes:
      - ./conf/tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
      - tempo-data:/var/tempo

  node-exporter:
    image: prom/node-exporter:latest
    container_name: internal-observability-node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    command: 
      - --path.rootfs=/host
      - --web.listen-address=:25910
    expose:
      - 25910
    volumes:
      - /:/host:ro,rslave

volumes:
  grafana-data:
  prometheus-data:
  loki-data:
  alloy-data:
  tempo-data:

networks:
  default:
    name: internal-observability-network
    external: true
